name: Badge Request
description: Request a badge that you would like to see be added to the current badge list.
title: "[Badge Request]: "
labels: ["📛 badge request"]
projects: ["inttter/md-badges"]
assignees:
  - inttter
body:
  - type: markdown
    attributes:
      value: |
        Before submitting this issue, make sure the badge does not **already exist** in this repository, and make sure it has a **valid** icon on [SimpleIcons](https://simpleicons.org).
  - type: input
    id: name
    attributes:
      label: Badge Name
      description: What is the name of the badge?
      placeholder: eg. React
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a short description about who/what the badge is for, such as a URL to a website.
      placeholder: This badge is for [NAME], which/who...
    validations:
      required: true